import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const assetRoot = resolve(root, 'src/client/assets')

const groups = {
  REACTIONS: Object.fromEntries([
    'idle',
    'skeptical', 'cheerful', 'apologetic', 'shocked', 'sleepy', 'proud', 'crying', 'angry',
    'thinking', 'relaxed', 'desk-confused', 'desk-coding', 'desk-done', 'desk-facepalm',
    'deepseek-rice', 'deepseek-pressure', 'blindfold', 'satiated', 'hungry', 'pillow', 'sleeping',
    'whip-defense', 'whip-frightened', 'whip-giggle',
  ].map(name => [name, name === 'idle' ? 'deepseek-idle' : `reaction-${name}`])),
  REACTION_FRAMES: {
    'idle-blink': 'frame-idle-blink',
    'desk-coding-hands-up': 'frame-desk-coding-hands-up',
    'thinking-keypress': 'frame-thinking-keypress',
  },
  DECORATIONS: { seal: 'decoration-seal' },
}

async function dataUrl(file) {
  const data = await readFile(resolve(assetRoot, `${file}.webp`))
  return `data:image/webp;base64,${data.toString('base64')}`
}

const blocks = []
let count = 0
for (const [exportName, files] of Object.entries(groups)) {
  const rows = []
  for (const [name, file] of Object.entries(files)) {
    rows.push(`  ${JSON.stringify(name)}: ${JSON.stringify(await dataUrl(file))},`)
    count += 1
  }
  blocks.push(`export const ${exportName} = Object.freeze({\n${rows.join('\n')}\n})`)
}

await writeFile(
  resolve(root, 'src/client/assets.generated.js'),
  `// Generated by scripts/embed-assets.mjs.\n${blocks.join('\n\n')}\n`,
)
console.log(`embedded ${count} complete character assets`)
