export const STYLES = `
[data-dsh-live2d-root] {
  --pet-blue:#5594f1; --pet-cyan:#75ddff;
  --pet-panel:color-mix(in srgb,var(--dsw-alias-bg-l1,#111d35) 90%,transparent);
  --pet-line:color-mix(in srgb,var(--dsw-alias-border-l2,#52698d) 58%,transparent);
  position:absolute; right:18px; bottom:14px; z-index:30; display:grid; justify-items:center; width:306px;
  pointer-events:none; filter:drop-shadow(0 16px 28px rgba(0,12,36,.2));
  transform:translate3d(var(--pet-drag-x,0),var(--pet-drag-y,0),0) scale(var(--pet-scale,1));transform-origin:100% 100%; color:var(--dsw-alias-text-primary,#eff7ff);
  font:500 11px/1.45 ui-rounded,"SF Pro Rounded","PingFang SC",system-ui,sans-serif;
}
[data-dsh-live2d-root] *{box-sizing:border-box}
.dsh-live2d-conversation,.dsh-live2d-bubble,.dsh-live2d-pending article{border:1px solid var(--pet-line);background:var(--pet-panel);box-shadow:0 12px 32px rgba(3,15,40,.18);backdrop-filter:blur(18px)}
.dsh-live2d-conversation{width:306px;max-height:230px;margin-bottom:7px;border-radius:15px;overflow:auto;pointer-events:auto;transition:max-height .35s ease,opacity .25s ease,transform .35s ease;scrollbar-width:thin}
.dsh-live2d-conversation[data-visible=false]{max-height:0;margin-bottom:0;border-width:0;opacity:0;transform:translateY(8px)}
.dsh-live2d-bubble{position:relative;z-index:3;width:260px;max-height:108px;margin:0 0 -15px;padding:11px 14px;border-radius:16px 16px 5px 16px;text-align:left;overflow:hidden;pointer-events:auto;transform-origin:80% 100%;transition:max-height .35s ease,margin .35s ease,padding .35s ease,opacity .25s ease,transform .35s ease;animation:dsh-pop .4s cubic-bezier(.2,.8,.25,1.2)}.dsh-live2d-bubble[data-visible=false]{max-height:0;margin-bottom:0;padding-top:0;padding-bottom:0;border-width:0;opacity:0;transform:translateY(8px) scale(.96)}.dsh-live2d-bubble span{display:block;font-weight:700}.dsh-live2d-bubble small{display:block;max-height:62px;margin-top:3px;overflow:auto;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:9px;white-space:pre-wrap;scrollbar-width:thin}.dsh-live2d-bubble[data-stream=true] small{overflow-x:auto;overflow-y:hidden;color:var(--dsw-alias-text-secondary,#b8c7df);line-height:1.55;white-space:nowrap;scrollbar-width:none}.dsh-live2d-bubble[data-stream=true] small::-webkit-scrollbar{display:none}.dsh-live2d-bubble[data-stream=true] small i{display:inline-block;width:1px;height:1em;margin-left:2px;vertical-align:-2px;background:var(--pet-cyan);animation:dsh-caret .72s step-end infinite}
.dsh-live2d-stage{position:relative;width:260px;height:244px}
.dsh-live2d-character{position:absolute;inset:0 auto auto 16px;width:228px;height:244px;padding:0;border:0;background:none;cursor:grab;pointer-events:auto;touch-action:none;-webkit-tap-highlight-color:transparent}.dsh-live2d-character:active{cursor:grabbing}.dsh-live2d-character:before{position:absolute;inset:auto 12px 10px;height:48px;border-radius:50%;background:radial-gradient(ellipse,color-mix(in srgb,var(--pet-blue) 26%,transparent),transparent 68%);content:"";filter:blur(10px)}
.dsh-live2d-sprites{position:absolute;inset:0;display:block;transform:none}.dsh-live2d-sprites img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 12px 9px rgba(0,10,34,.2));opacity:0;transform:none;transition:opacity .35s ease;user-select:none}.dsh-live2d-sprites img[data-active=true]{opacity:1;transform:none}.dsh-live2d-sprites img[data-frame=true],.dsh-live2d-sprites img[data-frame=true][data-active=true]{z-index:2;transform:none;transition:opacity .06s steps(1,end)}
.dsh-live2d-tools{position:relative;z-index:12;display:flex;gap:7px;height:34px;margin-top:4px;opacity:0;pointer-events:none;transform:translateY(-3px) scale(.94);transition:opacity .2s ease,transform .3s cubic-bezier(.2,.8,.2,1)}.dsh-live2d-stage:hover+.dsh-live2d-tools,.dsh-live2d-stage:focus-within+.dsh-live2d-tools,.dsh-live2d-tools:hover,.dsh-live2d-tools:focus-within{opacity:1;pointer-events:auto;transform:none}.dsh-live2d-tools button{display:flex;height:30px;padding:0 11px;align-items:center;gap:5px;border:1px solid var(--pet-line);border-radius:999px;background:var(--pet-panel);box-shadow:0 7px 18px rgba(3,15,40,.22);color:var(--dsw-alias-text-secondary,#b8c7df);font:inherit;cursor:pointer;backdrop-filter:blur(15px);transition:.2s ease}.dsh-live2d-tools button b{font:700 16px/1 system-ui,sans-serif}.dsh-live2d-tools button span{font-size:8px}.dsh-live2d-tools button:hover,.dsh-live2d-tools button:focus-visible{border-color:var(--pet-cyan);color:#fff;box-shadow:0 0 0 2px color-mix(in srgb,var(--pet-cyan) 20%,transparent),0 7px 18px rgba(3,15,40,.22);outline:0;transform:translateY(-2px)}
.dsh-live2d-pending{display:grid;gap:6px;padding:7px}.dsh-live2d-pending article{padding:9px;border-radius:12px}.dsh-live2d-pending article>strong,.dsh-live2d-pending legend{display:block;font-size:10px}.dsh-live2d-pending article>small,.dsh-live2d-pending fieldset>small{display:block;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:8px}.dsh-live2d-pending article>div,.dsh-live2d-pending fieldset>div{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}.dsh-live2d-pending button{padding:5px 8px;border:1px solid var(--pet-line);border-radius:7px;background:transparent;color:var(--dsw-alias-text-secondary,#b8c7df);font:inherit;cursor:pointer}.dsh-live2d-pending button[data-primary],.dsh-live2d-pending button[data-selected=true]{border-color:var(--pet-blue);background:color-mix(in srgb,var(--pet-blue) 25%,transparent);color:#fff}.dsh-live2d-pending fieldset{margin:0;padding:0;border:0}.dsh-live2d-pending input{width:100%;margin-top:6px;padding:6px 7px;border:1px solid var(--pet-line);border-radius:7px;background:rgba(0,0,0,.14);color:inherit;font:inherit}.dsh-live2d-pending>p{margin:0;color:#ff9eaa;font-size:9px}
.dsh-live2d-sessions{position:relative;display:grid;justify-items:center;width:270px;margin-top:7px;pointer-events:auto;transition:.35s ease}.dsh-live2d-sessions[data-visible=false]{display:none}.dsh-live2d-sessions button{position:relative;display:grid;grid-template-columns:7px minmax(0,1fr) auto;align-items:center;gap:7px;width:100%;height:34px;padding:7px 9px;border:1px solid var(--pet-line);border-radius:10px;background:var(--pet-panel);box-shadow:0 8px 20px rgba(3,15,40,.16);color:var(--dsw-alias-text-secondary,#b8c7df);font:inherit;text-align:left;cursor:pointer;backdrop-filter:blur(15px);transition:margin .28s ease,width .28s ease,transform .28s ease,opacity .2s ease,border-color .2s ease,box-shadow .2s ease,background .2s ease}.dsh-live2d-sessions button:hover{border-color:color-mix(in srgb,var(--pet-cyan) 68%,var(--pet-line));background:color-mix(in srgb,var(--pet-blue) 18%,var(--pet-panel))}.dsh-live2d-sessions button i{width:6px;height:6px;border-radius:50%;background:#f1bd5b}.dsh-live2d-sessions button i[data-running=true],.dsh-live2d-sessions button[data-current=true] i{background:var(--pet-cyan);box-shadow:0 0 8px var(--pet-cyan)}.dsh-live2d-sessions button span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh-live2d-sessions button small{color:var(--dsw-alias-text-tertiary,#8194b6);font-size:8px;white-space:nowrap}.dsh-live2d-session-focus{z-index:9;height:42px!important;padding:9px 11px!important;border-color:var(--pet-cyan)!important;border-radius:14px!important;background:color-mix(in srgb,var(--pet-blue) 22%,var(--pet-panel))!important;box-shadow:0 0 0 1px color-mix(in srgb,var(--pet-cyan) 42%,transparent),0 0 16px color-mix(in srgb,var(--pet-cyan) 58%,transparent),0 8px 20px rgba(3,15,40,.2)!important}.dsh-live2d-session-focus span{font-size:10px;font-weight:650}.dsh-live2d-session-list{display:grid;justify-items:center;gap:5px;width:246px;margin-top:6px}.dsh-live2d-session-list[data-visible=false]{display:none}.dsh-live2d-session-list>button[data-stacked=true]{margin-top:-24px;opacity:.84}.dsh-live2d-session-list>button:nth-of-type(4){z-index:6;width:calc(100% - 8px)}.dsh-live2d-session-list>button:nth-of-type(5){z-index:5;width:calc(100% - 18px)}.dsh-live2d-session-list>button:nth-of-type(6){z-index:4;width:calc(100% - 28px)}.dsh-live2d-session-list>button:nth-of-type(7){z-index:3;width:calc(100% - 38px)}.dsh-live2d-session-list:hover>button[data-stacked=true],.dsh-live2d-session-list:focus-within>button[data-stacked=true]{width:100%;margin-top:0;opacity:1}.dsh-live2d-session-list footer{margin-top:-18px;padding:23px 8px 3px;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:8px}
[data-dsh-live2d-root][data-collapsed=true]{--pet-scale:1!important;width:58px;justify-items:end}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-conversation,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-bubble,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-sessions,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-tools{display:none}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-stage,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-character{width:58px;height:68px}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-character{left:0}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-sprites{right:0;bottom:0;left:auto;top:auto;width:228px;height:244px;animation:none!important;transition:none!important;transform:scale(.28)!important;transform-origin:100% 100%}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-sprites img{transition:none!important}
[data-dsh-live2d-root][data-celebrating=true] .dsh-live2d-character{animation:dsh-pet-jump .6s cubic-bezier(.3,.9,.4,1.2) 2}
[data-dsh-live2d-root][data-celebrating=true] .dsh-live2d-sprites img[data-active=true]{filter:drop-shadow(0 12px 9px rgba(0,10,34,.2)) drop-shadow(0 0 14px var(--pet-cyan))}
.dsh-live2d-confetti{position:absolute;z-index:5;inset:0;pointer-events:none;overflow:visible}
.dsh-live2d-confetti i{position:absolute;top:-8px;left:var(--cf-x,50%);width:7px;height:12px;border-radius:2px;background:var(--cf-color,#75ddff);opacity:0;animation:dsh-confetti-fall var(--cf-dur,1.5s) ease-in var(--cf-delay,0s) forwards;transform:rotate(var(--cf-rot,0deg))}
.dsh-live2d-mute-hint{position:absolute;z-index:6;right:6px;top:6px;font-size:15px;opacity:0;pointer-events:none;transition:opacity .25s ease}
.dsh-live2d-mute-hint[data-visible=true]{opacity:1}
.dsh-live2d-diag{position:relative;z-index:14;width:250px;margin-bottom:7px;padding:10px 12px;border:1px solid var(--pet-line);border-radius:13px;background:var(--pet-panel);box-shadow:0 12px 32px rgba(3,15,40,.22);backdrop-filter:blur(18px);pointer-events:auto}
.dsh-live2d-diag header{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:11px}
.dsh-live2d-diag header button{border:0;background:none;color:var(--dsw-alias-text-tertiary,#8194b6);cursor:pointer;font-size:11px;padding:2px}
.dsh-live2d-diag header button:hover{color:#fff}
.dsh-live2d-diag dl{display:grid;grid-template-columns:1fr 1fr;gap:4px 10px;margin:8px 0 0;font-size:9px}
.dsh-live2d-diag dl>div{display:flex;justify-content:space-between;gap:6px}
.dsh-live2d-diag dt{color:var(--dsw-alias-text-tertiary,#8194b6)}
.dsh-live2d-diag dd{margin:0;color:var(--dsw-alias-text-primary,#eff7ff);text-align:right}
.dsh-live2d-diag footer{display:flex;align-items:center;gap:6px;margin-top:8px;font-size:9px;color:var(--dsw-alias-text-tertiary,#8194b6)}
.dsh-live2d-diag footer button{padding:3px 8px;border:1px solid var(--pet-line);border-radius:7px;background:transparent;color:var(--dsw-alias-text-secondary,#b8c7df);font:inherit;cursor:pointer}
.dsh-live2d-diag footer button:hover{border-color:var(--pet-cyan);color:#fff}
.dsh-live2d-diag footer label{display:flex;align-items:center;gap:5px;margin-right:auto}
.dsh-live2d-diag footer input[type=range]{width:76px;height:3px;accent-color:var(--pet-cyan);cursor:pointer}
@keyframes dsh-pop{from{opacity:0;transform:translateY(5px) scale(.94)}}@keyframes dsh-caret{50%{opacity:0}}
@keyframes dsh-pet-jump{0%,100%{transform:translateY(0)}35%{transform:translateY(-22px) scale(1.04)}60%{transform:translateY(0) scale(.98)}}
@keyframes dsh-confetti-fall{0%{opacity:0;transform:translateY(-8px) rotate(var(--cf-rot,0deg))}12%{opacity:1}100%{opacity:0;transform:translateY(230px) translateX(var(--cf-drift,0px)) rotate(calc(var(--cf-rot,0deg) + 320deg))}}
@media(max-width:760px){[data-dsh-live2d-root]{right:7px;bottom:74px;width:286px}.dsh-live2d-conversation{width:286px}.dsh-live2d-sessions{width:256px}.dsh-live2d-session-list{width:232px}}
@media(hover:none){.dsh-live2d-tools{opacity:.72;pointer-events:auto;transform:none}}
@media(prefers-reduced-motion:reduce){[data-dsh-live2d-root] *,[data-dsh-live2d-root] *:before{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
`

export function installStyles() {
  const existing = document.querySelector('style[data-plugin="deepseek-pet"]')
  if (existing) return () => {}
  const style = document.createElement('style')
  style.dataset.plugin = 'deepseek-pet'
  style.textContent = STYLES
  document.head.append(style)
  return () => style.remove()
}
