#!/usr/bin/env node
/**
 * Aggregate plugin generator for the dsh-web-ui monorepo.
 *
 * An aggregate bundle is a plain carrier package whose cordis.patch.yml is the
 * concatenation of its child plugins' insert rows and whose package.json
 * dependencies pull in every child with "workspace:*". The DSH loader
 * resolves patch rows from the profile root, so the children are installed as
 * normal dependencies (pnpm hoists them to the top level in the default
 * hoisted layout); the README documents the hoist setting for strict-layout
 * profiles.
 *
 * Usage:
 *   node scripts/aggregate.mjs            # regenerate + write everything
 *   node scripts/aggregate.mjs --check    # verify only; exit 1 on any drift
 *
 * Each aggregate package carries a hand-written aggregate.yml manifest:
 *
 *   patchFrom:
 *     - ../skins/skin-center
 *   deps:
 *     - ../skins/skin-center
 *     - ../qq98
 *
 *   - patchFrom entries contribute their child's cordis.patch.yml insert rows
 *     to the aggregate patch (nested aggregates expand recursively, in
 *     patchFrom order, with per-source comment headers);
 *   - deps entries are resolved to each child's package.json "name" and
 *     written into the aggregate's dependencies as "workspace:*".
 *
 * Idempotent: safe to rerun at any time. Writes only inside the aggregate
 * packages it owns; never touches other packages or git state.
 */
import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join, relative, resolve as resolvePath } from 'node:path'
import { fileURLToPath } from 'node:url'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolvePath(SCRIPT_DIR, '..')
const CHECK = process.argv.includes('--check')

const PATCH_HEADER = [
  '# AUTO-GENERATED by scripts/aggregate.mjs — do not edit',
  '# This file is derived from the aggregate.yml manifest in this package;',
  '# edit aggregate.yml and rerun `node scripts/aggregate.mjs`.',
]

/** Directories directly under a path (non-recursive, sorted). */
function listSubdirs(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((entry) => {
      try {
        return statSync(join(dir, entry)).isDirectory()
      } catch {
        return false
      }
    })
    .sort()
}

/** Find every aggregate package: packages/* and packages/skins/* with an aggregate.yml. */
function findAggregates() {
  const candidates = []
  for (const name of listSubdirs(join(REPO_ROOT, 'packages'))) {
    candidates.push(join(REPO_ROOT, 'packages', name))
  }
  for (const name of listSubdirs(join(REPO_ROOT, 'packages', 'skins'))) {
    candidates.push(join(REPO_ROOT, 'packages', 'skins', name))
  }
  return candidates
    .filter((dir) => existsSync(join(dir, 'aggregate.yml')))
    .map((pkgDir) => ({ pkgDir, ymlPath: join(pkgDir, 'aggregate.yml') }))
}

/**
 * Parse the hand-written manifest. YAML subset on purpose: comment lines and
 * blank lines are skipped, "<key>:" lines start a section, "- <value>" lines
 * belong to the current section.
 */
function parseManifest(ymlPath) {
  const manifest = { patchFrom: [], deps: [], self: null }
  let section = null
  for (const raw of readFileSync(ymlPath, 'utf8').split(/\r?\n/)) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const sectionMatch = line.match(/^[A-Za-z0-9_-]+:\s*$/)
    if (sectionMatch) {
      section = line.slice(0, -1)
      continue
    }
    const entryMatch = line.match(/^-\s+(.+)$/)
    if (!entryMatch) continue
    const entry = entryMatch[1].trim().replace(/\s+#.*$/, '')
    if (section === 'patchFrom') manifest.patchFrom.push(entry)
    else if (section === 'deps') manifest.deps.push(entry)
    else if (section === 'self') {
      if (manifest.self !== null && manifest.self !== entry) {
        console.warn(`aggregate.yml defines several self entries (${manifest.self}, ${entry}); keeping the last one`)
      }
      manifest.self = entry
    }
  }
  return manifest
}

/** Extract {id, name} rows from a child's cordis.patch.yml (fixed format: "- id:" immediately followed by "name:"). */
function parsePatchRows(patchPath, errors) {
  const significant = []
  for (const [i, raw] of readFileSync(patchPath, 'utf8').split(/\r?\n/).entries()) {
    const text = raw.trim()
    if (text && !text.startsWith('#')) significant.push({ text, line: i + 1 })
  }
  const rows = []
  for (let i = 0; i < significant.length; i++) {
    const idMatch = significant[i].text.match(/^-\s*id:\s*(\S+)\s*$/)
    if (!idMatch) continue
    const next = significant[i + 1]
    if (!next) {
      errors.push(`${patchPath}:${significant[i].line}: "- id:" row without a following "name:" line`)
      continue
    }
    const nameMatch = next.text.match(/^name:\s*(['"])([^'"]+)\1\s*$/)
      || next.text.match(/^name:\s*(\S+)\s*$/)
    if (!nameMatch) {
      errors.push(`${patchPath}:${next.line}: expected a "name:" line after "- id: ${idMatch[1]}"`)
      continue
    }
    rows.push({ id: idMatch[1], name: nameMatch[2] ?? nameMatch[1] })
    i++ // consume the paired name line
  }
  return rows
}

/**
 * Collect patch rows for one patchFrom entry. Aggregates expand recursively
 * (cycle-guarded); leaf bundles contribute the rows parsed from their own
 * cordis.patch.yml. Every block remembers its leaf entry and the chain of
 * aggregate entries it was reached through, for the comment headers.
 */
function collectRows(pkgDir, entry, via, visited, errors, blocks) {
  const manifestPath = join(pkgDir, 'aggregate.yml')
  if (existsSync(manifestPath)) {
    if (visited.has(pkgDir)) {
      errors.push(`aggregate cycle: ${[...visited, pkgDir].join(' -> ')}`)
      return
    }
    visited.add(pkgDir)
    const manifest = parseManifest(manifestPath)
    for (const sub of manifest.patchFrom) {
      const subDir = resolvePath(pkgDir, sub)
      if (!existsSync(subDir)) {
        errors.push(`patchFrom target not found: ${manifestPath} -> ${sub} (${subDir})`)
        continue
      }
      collectRows(subDir, sub, [...via, entry], visited, errors, blocks)
    }
    visited.delete(pkgDir)
    return
  }
  const patchPath = join(pkgDir, 'cordis.patch.yml')
  if (!existsSync(patchPath)) {
    errors.push(`patchFrom target has no cordis.patch.yml: ${pkgDir} (via ${[...via, entry].join(' -> ')})`)
    return
  }
  const rows = parsePatchRows(patchPath, errors)
  if (rows.length === 0) {
    errors.push(`no plugin rows parsed from ${patchPath}`)
    return
  }
  blocks.push({ entry, via, rows })
}

/** Render the aggregate cordis.patch.yml: header + per-source insert blocks. */
function renderPatch(blocks) {
  const lines = [...PATCH_HEADER]
  for (const block of blocks) {
    const chain = block.via.length ? ` (via ${block.via.join(' -> ')})` : ''
    lines.push('', `# from ${block.entry}${chain}`, '- insert:')
    for (const row of block.rows) {
      lines.push(`    - id: ${row.id}`)
      lines.push(`      name: '${row.name}'`)
    }
  }
  return lines.join('\n') + '\n'
}

/** Resolve manifest entries to their package names (read from each child's package.json). */
function resolveEntries(pkgDir, entries, section, errors) {
  const resolved = []
  for (const entry of entries) {
    const depDir = resolvePath(pkgDir, entry)
    const pkgPath = join(depDir, 'package.json')
    if (!existsSync(pkgPath)) {
      errors.push(`${section} target has no package.json: ${join(pkgDir, 'aggregate.yml')} -> ${entry} (${pkgPath})`)
      continue
    }
    let name
    try {
      name = JSON.parse(readFileSync(pkgPath, 'utf8')).name
    } catch (e) {
      errors.push(`cannot read ${pkgPath}: ${e.message}`)
      continue
    }
    if (!name) {
      errors.push(`no "name" field in ${pkgPath}`)
      continue
    }
    resolved.push({ name, entry })
  }
  return resolved
}

/**
 * Rebuild the aggregate package.json so every manifest deps entry becomes a
 * "workspace:*" dependency; other fields are preserved, and any leftover
 * peerDependencies field is removed. The loader resolves patch rows from the
 * profile root, and pnpm installs these children as normal dependencies
 * (hoisting them to the top level in the default layout).
 */
function renderPackageJson(pkgPath, resolvedDeps) {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
  const next = {}
  for (const { name } of resolvedDeps) next[name] = 'workspace:*'
  for (const key of Object.keys(pkg.dependencies ?? {}).filter((k) => !(k in next)).sort()) {
    next[key] = pkg.dependencies[key]
  }
  if (Object.keys(next).length) pkg.dependencies = next
  else delete pkg.dependencies
  delete pkg.peerDependencies
  return JSON.stringify(pkg, null, 2) + '\n'
}

console.log(`[aggregate] scanning ${join(REPO_ROOT, 'packages')} for aggregate.yml manifests...`)
const aggregates = findAggregates()
if (aggregates.length === 0) {
  console.log('[aggregate] no aggregate.yml found; nothing to do.')
  process.exit(0)
}

const errors = []
const results = []
for (const { pkgDir, ymlPath } of aggregates) {
  const rel = relative(REPO_ROOT, pkgDir)
  const manifest = parseManifest(ymlPath)
  const blocks = []
  const visited = new Set()
  for (const entry of manifest.patchFrom) {
    const target = resolvePath(pkgDir, entry)
    if (!existsSync(target)) {
      errors.push(`patchFrom target not found: ${ymlPath} -> ${entry} (${target})`)
      continue
    }
    collectRows(target, entry, [], visited, errors, blocks)
  }
  if (manifest.self) {
    // self: the aggregate package loads ITS OWN plugin (host + client half)
    // through one patch row, e.g. the compat shim living inside web-ui-all.
    // unshift keeps the self block FIRST in the rendered patch so its ordering
    // does not drift when the patchFrom entries change.
    if (!/^[a-z0-9-]+$/.test(manifest.self)) {
      errors.push(`invalid self entry '${manifest.self}' (must match ^[a-z0-9-]+$); skipping self block`)
    } else {
      let selfName
      try {
        selfName = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')).name
      } catch (e) {
        errors.push(`cannot read self package name: ${e.message}`)
      }
      if (selfName) blocks.unshift({ entry: 'self', via: [], rows: [{ id: manifest.self, name: selfName }] })
    }
  }
  if (manifest.patchFrom.length === 0 && !manifest.self) {
    console.log(`[aggregate] WARN ${rel}: aggregate.yml has no patchFrom entries (patch would be empty)`)
  }
  const patch = renderPatch(blocks)
  const resolvedDeps = resolveEntries(pkgDir, manifest.deps, 'deps', errors)
  const pkgJson = renderPackageJson(join(pkgDir, 'package.json'), resolvedDeps)
  results.push({ rel, blocks, patch, resolvedDeps, pkgJson })
}

let failed = false
if (errors.length) {
  for (const e of errors) console.error(`[aggregate] ERROR ${e}`)
  failed = true
}

if (failed) {
  console.error(CHECK ? '[aggregate] check FAILED: generated content differs from disk' : '[aggregate] FAILED: see errors above; no files written')
  process.exit(1)
}

for (const r of results) {
  const patchPath = join(REPO_ROOT, r.rel, 'cordis.patch.yml')
  const pkgPath = join(REPO_ROOT, r.rel, 'package.json')
  if (CHECK) {
    const diffs = []
    if (!existsSync(patchPath) || readFileSync(patchPath, 'utf8') !== r.patch) diffs.push(relative(REPO_ROOT, patchPath))
    if (!existsSync(pkgPath) || readFileSync(pkgPath, 'utf8') !== r.pkgJson) diffs.push(relative(REPO_ROOT, pkgPath))
    if (diffs.length) {
      for (const d of diffs) console.log(`[aggregate] check: ${d} differs from generated content`)
      failed = true
    } else {
      const rows = r.blocks.reduce((n, b) => n + b.rows.length, 0)
      console.log(`[aggregate] check OK: ${r.rel} (${rows} row(s), ${r.resolvedDeps.length} dep(s))`)
    }
  } else {
    writeFileSync(patchPath, r.patch)
    const rows = r.blocks.reduce((n, b) => n + b.rows.length, 0)
    console.log(`[aggregate] wrote ${relative(REPO_ROOT, patchPath)} (${r.blocks.length} source block(s), ${rows} row(s))`)
    writeFileSync(pkgPath, r.pkgJson)
    console.log(`[aggregate] wrote ${relative(REPO_ROOT, pkgPath)} (${r.resolvedDeps.length} workspace dep(s))`)
  }
}

if (failed) {
  console.error('[aggregate] check FAILED: generated content differs from disk')
  process.exit(1)
}
console.log('[aggregate] done')
